In [39]:
#! /usr/bin/env python3
# -*- coding: utf-8 -*-

### Vorlagendatei für die Übungen zur Datenverarbeitung ###

# Bitte ergänzen Sie hier die Daten der Abgebenden. Ersetzen Sie nur
# die Punkte ('...'), aber lassen Sie den Rest der Zeilen und ihre Reihenfolge
# ansonsten unverändert, da Ihre Abgabe sonst nicht elektronisch verarbeitet
# werden kann.
#
# 1)
# Matrikelnummer: 461634
# Name: Christina Lei
# Email: christina.lei@rwth-aachen.de
#
# 2)
# Matrikelnummer: 454171
# Name: Zoe Leona Martens
# Email: zoe.martens@rwth-aachen.de

In [40]:
### Aufgabe 2 Python arrays

In [41]:
#1
import numpy as np

a= np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [42]:
#2 ersten 5 Elemente
a[:5]

array([0, 1, 2, 3, 4])

In [43]:
#3 jedes zweites Element 
a[::2]

array([0, 2, 4, 6, 8])

In [44]:
#4 letztes Element 
a[-1]

9

In [45]:
#5 letzten 5 Elemente 
a[-5:]

array([5, 6, 7, 8, 9])

In [46]:
#6 alles außer letzten beiden Elemente
a[:-2]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [88]:
#7 alle Elemente in umgekehrter Reihenfolge 1
res=a[::-1]
print (res)
#wo ist die 0?

[9, 8, 7, 6, 5, 4, 3, 2, 1]


In [68]:
#7 alle Elemente in umgekehrter Reihenfolge 3
print(a)
a[::-1]

[1, 2, 3, 4, 5, 6, 7, 8, 9]


[9, 8, 7, 6, 5, 4, 3, 2, 1]

In [90]:
#8 Ersten drei Elemente in umgekehrter Reihenfolge
print(a)
u=a[:3]
print (u)
u[::-1]

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3]


[3, 2, 1]

In [78]:
#9 letzten drei Elemente in umgekehrter Reihenfolge 
print (a)
k=a[-3:]
print (k)
k[::-1]

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[7, 8, 9]


[9, 8, 7]

In [91]:
#10 Alles außer letzten beiden Elemente in umgekehrter Reihenfolge
import numpy as np
l=a[:7]
l.reverse()
h=a[-2:]
np.concatenate((l,h))

#https://statologie.de/arrays-verketten-python/

array([7, 6, 5, 4, 3, 2, 1, 8, 9])

In [85]:
#10 Alles außer letzten beiden Elemente in umgekehrter Reihenfolge
print (a)
p=a[:7]
print (p)
k=p[::-1]
print (k)
print (k+a[-2:])

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7]
[7, 6, 5, 4, 3, 2, 1]
[7, 6, 5, 4, 3, 2, 1, 8, 9]
